wildcatMicroFund/Models/EmailTemplate.cs
using System.ComponentModel.DataAnnotations;

namespace wildcatMicroFund.Models
{
    public class EmailTemplate
    {
        [Key]
        public int Id { get; set; }
        [Required]
        [Display(Name = "TemplateName")]
        public string? EmailTemplateName { get; set; }
        [Required]
        [Display(Name = "TemplateContent")]
        public string? TemplateContent { get; set; }
        [Required]
        [Display(Name = "TemplateSubject")]
        public string? TemplateSubject { get; set; }
        public DateTime ModifiedDate { get; set; }
    }
}

wildcatMicroFund/Areas/Admin/Controllers/EmailTemplates/EmailTemplatesController.cs
using Microsoft.AspNetCore.Mvc;
using wildcatMicroFund.Interfaces;
using wildcatMicroFund.Models;

[Area("Admin")]
public class EmailTemplatesController : Controller
{
    private readonly IUnitOfWork _unitOfWork;
    public EmailTemplatesController(IUnitOfWork unitOfWork) 
    {
        _unitOfWork = unitOfWork;
    }
    public ViewResult Index() 
    {
        IEnumerable<EmailTemplate> objEmailTemplateList = _unitOfWork.EmailTemplate.GetAll();
        return View(objEmailTemplateList);
    }
    [HttpGet]
    public ViewResult Create() 
    {
        return View();
    }
    [HttpGet]
    public IActionResult Edit(int? id) 
    {
        if (id == null || id == 0) 
        {
            return NotFound();
        }
        var emailTemplateFromDb = _unitOfWork.EmailTemplate.Get(c => c.Id == id);
        if (emailTemplateFromDb == null) 
        {
            return NotFound();
        }
        return View(emailTemplateFromDb);
    }
    [HttpGet]
    public IActionResult Delete(int? id) 
    {
        if (id == null || id == 0) 
        {
            return NotFound();
        }
        var emailTemplateFromDb = _unitOfWork.EmailTemplate.Get(c => c.Id == id);
        if (emailTemplateFromDb == null) 
        {
            return NotFound();
        }
        return View(emailTemplateFromDb);
    }
    [HttpPost]
    [ValidateAntiForgeryToken]
    public IActionResult Create(EmailTemplate obj) 
    {
        if (ModelState.IsValid) 
        {
            obj.ModifiedDate = DateTime.Now;
            _unitOfWork.EmailTemplate.Add(obj);
            _unitOfWork.Commit();
            TempData["success"] = "Email Template created Successfully";
            return RedirectToAction("Index");
        }
        return View(obj);
    }
    [HttpPost]
    [ValidateAntiForgeryToken]
    public IActionResult Edit(EmailTemplate obj) 
    {
        if (ModelState.IsValid) 
        {
            obj.ModifiedDate = DateTime.Now;
            _unitOfWork.EmailTemplate.Update(obj);
            _unitOfWork.Commit();
            TempData["success"] = "Email Template updated Successfully";
            return RedirectToAction("Index");
        }
        return View(obj);
    }
    [HttpPost, ActionName("Delete")]
    public IActionResult DeletePost(int? id) 
    {
        var obj = _unitOfWork.EmailTemplate.Get(c => c.Id == id);
        if (obj == null) 
        {
            return NotFound();
        }
        _unitOfWork.EmailTemplate.Delete(obj);
        _unitOfWork.Commit();
        TempData["success"] = "Email Template was deleted Successfully";
        return RedirectToAction("Index");
    }

}

wildcatMicroFund/Areas/Admin/Views/EmailTemplates/Create.cshtml
@model EmailTemplate
@{
    ViewData["Title"] = "Create Email Template";
}
<form method="post">
    <div class="border p-3 mt-4">
        <div class="row pb-2">
            <h2 class="text-primary">Create Template</h2>
            <hr />
        </div>
        @*<div asp-validation-summary="All"></div>*@
        <div class="mb-3">
            <label asp-for="EmailTemplateName"></label>
            <input asp-for="EmailTemplateName" class="form-control" />
            <span asp-validation-for="EmailTemplateName" class="text-danger"></span>
        </div>
                <div class="mb-3">
            <label asp-for="TemplateSubject"></label>
            <input asp-for="TemplateSubject" class="form-control" />
            <span asp-validation-for="TemplateSubject" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="TemplateContent"></label>
            @*<input asp-for="TemplateContent" class="form-control" />*@
            @*<textarea asp-for="TemplateContent" class="form-control"></textarea>*@
            <textarea id="mytextarea" class="form-control" style="height:200px;" asp-for="TemplateContent"></textarea>
            <span asp-validation-for="TemplateContent" class="text-danger"></span>
        </div>
        <button type="submit" class="btn btn-primary" style="width:150px">Create</button>
        <a asp-controller="EmailTemplates" asp-action="Index" class="btn btn-secondary" style="width:150px">
            Back to List
        </a>
    </div>
</form>

@section Scripts {
    @{
        <partial name="_ValidationScriptsPartial" />
            <script>
      tinymce.init({
        selector: '#mytextarea'
      });
    </script>
    }
    }

wildcatMicroFund/Areas/Admin/Views/EmailTemplates/Delete.cshtml
@model EmailTemplate
@{
    ViewData["Title"] = "Delete Email Template";
}
<form method="post">
    <div class="border p-3 mt-4">
        <div class="row pb-2">
            <h2 class="text-primary">Delete Template</h2>
            <hr />
        </div>
        <!--Needed becasue all other items are disabled-->
        <input asp-for="Id" hidden />
        @*<div asp-validation-summary="All"></div>*@
        <div class="mb-3">
            <label asp-for="EmailTemplateName"></label>
            <input asp-for="EmailTemplateName" disabled class="form-control" />

        </div>
        <div class="mb-3">
            <label asp-for="TemplateContent"></label>
            <input asp-for="TemplateContent" disabled class="form-control" />

        </div>
        <button type="submit" class="btn btn-danger" style="width:150px">Delete</button>
        <a asp-controller="EmailTemplates" asp-action="Index" class="btn btn-secondary" style="width:150px">
            Back to List
        </a>
    </div>
</form>

@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial" />
    }
    }

wildcatMicroFund/Areas/Admin/Views/EmailTemplates/Edit.cshtml
@model EmailTemplate
@{
    ViewData["Title"] = "Edit Email Template";
}
<form method="post">
    <div class="border p-3 mt-4">
        <div class="row pb-2">
            <h2 class="text-primary">Edit Template</h2>
            <hr />
        </div>
        @*<div asp-validation-summary="All"></div>*@
        <div class="mb-3">
            <label asp-for="EmailTemplateName"></label>
            <input asp-for="EmailTemplateName" class="form-control" />
            <span asp-validation-for="EmailTemplateName" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="TemplateSubject"></label>
            <input asp-for="TemplateSubject" class="form-control" />
            <span asp-validation-for="TemplateSubject" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="TemplateContent"></label>
            @*<input asp-for="TemplateContent" class="form-control" />*@
            <textarea id="mytextarea" class="form-control" style="height:200px;" asp-for="TemplateContent"></textarea>
            <span asp-validation-for="TemplateContent" class="text-danger"></span>
        </div>
        <button type="submit" class="btn btn-primary" style="width:150px">Update</button>
        <a asp-controller="EmailTemplates" asp-action="Index" class="btn btn-secondary" style="width:150px">
            Back to List
        </a>
    </div>
</form>

@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial" />
                    <script>
      tinymce.init({
        selector: '#mytextarea'
      });
    </script>
    }
    }

wildcatMicroFund/Areas/Admin/Views/EmailTemplates/Index.cshtml
@{
    ViewData["Title"] = "Email Templates";
}
<div class="container p-3">
    <div class="row pt-4">
        <div class="col-6">
            <h2 class="text-primary">Email Templates</h2>
        </div>
        <div class="col-6 text-end">
            <a asp-controller="EmailTemplates" asp-action="Create" class="btn btn-primary">
                <i class="bi bi-plus-circle"></i>Create New Template
            </a>
        </div>
    </div>
    <br /><br />

    <table class="table table-bordered table-striped" style="width:100%">
        <thead>
            <tr>
                <th>
                    Template Name
                </th>
                <th>
                    Last Modified
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var obj in Model)
            {
                <tr>
                    <td width="50%">
                        @obj.EmailTemplateName
                    </td>
                    <td width="15%">
                        @obj.ModifiedDate.ToString("MM/dd/yyyy")
                    </td>
                    <td>
                        <div class="w-75 btn-group" role="group">
                            <a asp-controller="EmailTemplates" asp-action="Edit" asp-route-id="@obj.Id"
                           class="btn btn-primary mx-2"> <i class="bi bi-pencil-square"></i> Edit</a>
                            <a asp-controller="EmailTemplates" asp-action="Delete" asp-route-id="@obj.Id"
                           class="btn btn-danger mx-2"> <i class="bi bi-trash-fill"></i> Delete</a>
                        </div>
                    </td>
                </tr>
            }
        </tbody>

    </table>
</div>