wildcatMicroFund/Areas/Mentor/Controllers/ReviewApplications/ReviewApplicationsController.cs
using Microsoft.AspNetCore.Identity.UI.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Linq;
using System.Security.Claims;
using wildcatMicroFund.Areas.Mentor.ViewModels;
using wildcatMicroFund.Data;
using wildcatMicroFund.Interfaces;
using wildcatMicroFund.Models;

[Area("Mentor")]
public class ReviewApplicationsController : Controller
{
    [BindProperty]
    public ReviewApplicationVM ReviewApplicationObj { get; set; }


    private readonly IUnitOfWork _unitOfWork;
    private readonly IWebHostEnvironment _hostEnvironment;
    private readonly IEmailSender _emailSender;
    public ReviewApplicationsController(IUnitOfWork unitOfWork, IWebHostEnvironment hostEnvironment, IEmailSender emailSender)//Dependency Injection & path to wwwroot folder
    {
        _unitOfWork = unitOfWork;
        _hostEnvironment = hostEnvironment;
        _emailSender = emailSender;
    }


    public ViewResult Index()
    {
        var claimsIdentity = (ClaimsIdentity)User.Identity;
        var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);
           
        IEnumerable<ApplicationStatus> AdminReviewApplication = _unitOfWork.ApplicationStatus.List(a => a.Status.StatusDesc == "Mentor Phase", null, "Application,Status");//WHERE, ORDERBY, JOIN
        return View(AdminReviewApplication);
    }

    [HttpGet]
    public IActionResult Upsert(int? id, int? appId) //optional id needed with edit mode vs create
    {

        var stati = _unitOfWork.Status.List();
        var mentors = _unitOfWork.ApplicationUser.List(null, null, "AspNetRoles");

        ReviewApplicationObj = new ReviewApplicationVM
        {
            UserAssignment = new UserAssignment(),
            AssignedUsers = _unitOfWork.UserAssignment.List(u => u.Application.Id == appId, u => u.Application.Id, "Application,ApplicationUser,UserApplicationAssignmentType"),
            ReviewApplication = new ApplicationStatus(),
            Application = _unitOfWork.Application.Get(a => a.Id == appId),
            Status = _unitOfWork.Status.Get(s => s.StatusID == id),
            StatusList = stati.Select(f => new SelectListItem { Value = f.StatusID.ToString(), Text = f.StatusDesc }),
            MentorList = mentors.Select(m => new SelectListItem { Value = m.Id, Text = m.FullName})
        };

        if (id != null)
        {
            ReviewApplicationObj.ReviewApplication = _unitOfWork.ApplicationStatus.Get(u => u.AppStatId == id, true);
            if (ReviewApplicationObj == null)
            {
                return NotFound();
            }
        }

        return View(ReviewApplicationObj);
    }

    [HttpPost]
    public IActionResult Upsert()
    {

        if (!ModelState.IsValid)
        {
            return View();
        }
        var claimsIdentity = (ClaimsIdentity)User.Identity;
        var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);

        ReviewApplicationObj.ReviewApplication.StatusDate = DateTime.Now;
        ReviewApplicationObj.ReviewApplication.UserID = claim.Value;
        _unitOfWork.ApplicationStatus.Update(ReviewApplicationObj.ReviewApplication);

        _unitOfWork.Commit();

        // Send an email
        var appInfo = _unitOfWork.Application.GetById(ReviewApplicationObj.ReviewApplication.ApplicationId);
        var newStatus = ReviewApplicationObj.ReviewApplication.StatusId;
        if (newStatus == 4)
        {
            _emailSender.SendEmailAsync("wildcatmicrofund@yahoo.com", "[WMF] Application Ready for Pitch Event", "<p>The " + appInfo.CompanyName + " application is now ready for pitch event assignment.</p>&nbsp;<p>Review applications here:&nbsp;</p><p>http://wildcatmicrofund-001-site1.gtempurl.com/Admin/AdminReviewApplications</p>");
        }
        return RedirectToAction("Index");
    }
}

wildcatMicroFund/Areas/Mentor/Views/ReviewApplications/Index.cshtml
@model IEnumerable<ApplicationStatus>

@{
    ViewData["Title"] = "Review Application";
}

<div class="container p-3">
    <div class="row pt-4">
        <div class="col-6">
            <h2 class="text-primary">Application List</h2>
        </div>
    </div>
    <br /><br />

    <table class="table table-bordered table-striped" style="width:100%">
        <thead>
            <tr>
                <th>
                    Company Name
                </th>
                <th>
                    Status
                </th>
            </tr>
        </thead>
        <tbody>
            @foreach (var obj in Model)
            {
                <tr>
                    <td width="50%">
                        @obj.Application.CompanyName
                    </td>                    
                    <td width="40%">
                        @obj.Status.StatusDesc
                    </td>
                    <td>
                        <div class="w-75 btn-group" role="group">
                           <a asp-area="Admin" asp-controller="AdminReviewApplications" asp-action="Upsert" asp-route-id="@obj.AppStatId" asp-route-appId="@obj.Application.Id" class="btn btn-primary mx-2"> <i class="bi bi-pencil-square"></i>Review</a>
                        </div>
                    </td>
                </tr>
            }
        </tbody>

    </table>
</div>

wildcatMicroFund/Areas/Mentor/Views/ReviewApplications/MentorIndex.cshtml
@model IEnumerable<ApplicationStatus>

@{
    ViewData["Title"] = "Review Application";
}

<div class="container p-3">
    <div class="row pt-4">
        <div class="col-6">
            <h2 class="text-primary">Application List</h2>
        </div>
    </div>
    <br /><br />

    <table class="table table-bordered table-striped" style="width:100%">
        <thead>
            <tr>
                <th>
                    Company Name
                </th>
                <th>
                    Status
                </th>
            </tr>
        </thead>
        <tbody>
            @foreach (var obj in Model)
            {
                <tr>
                    <td width="50%">
                        @obj.Application.CompanyName
                    </td>
                    <td width="40%">
                        @obj.Status.StatusDesc
                    </td>
                    <td>
                        <div class="w-75 btn-group" role="group">
                            <a asp-area="Mentor" asp-controller="ReviewApplications" asp-action="Upsert" asp-route-id="@obj.AppStatId" asp-route-appId="@obj.Application.Id" asp-route-statId="@obj.Status.StatusID"
                           class="btn btn-primary mx-2"> <i class="bi bi-pencil-square"></i>Review</a>
                        </div>
                    </td>
                </tr>
            }
        </tbody>

    </table>
</div>

wildcatMicroFund/Areas/Mentor/Views/ReviewApplications/Upsert.cshtml
@model wildcatMicroFund.Areas.Mentor.ViewModels.ReviewApplicationVM
@{
    ViewData["Title"] = "Update Application";
}
<form method="post" asp-controller="ReviewApplications" asp-action="Upsert" enctype="multipart/form-data">
    <div class="container">
        <div class="row px-2 mx-2 backgroundWhite border">
            @* All for Model validation and HTML validation *@
            <div asp-validation-summary="All" class="text-danger"></div>
            <div class="col-12 px-3" style="border-bottom:1px solid #325d88">
                <h2 class="text-primary">Update Application - @Model.Application.CompanyName</h2>
            </div>
            <div class="col-11 pt-3 offset-1">
                <div class="form-group row m-2">
                    <div class="col-4">
                        <h4>Company Name:</h4>
                    </div>
                    <div class="col-6">
                        <h4>@Model.Application.CompanyName</h4>
                    </div>
                </div>
                @foreach (var user in Model.AssignedUsers)
                {
                    <div class="form-group row m-2">
                        <div class="col-4">
                            <h4>@user.UserApplicationAssignmentType.UserApplicationAssignmentDesc Name:</h4>
                        </div>
                        <div class="col-6">
                            <h4>@user.ApplicationUser.FullName</h4>
                        </div>
                    </div>
                }

                <div class="form-group row ">
                    <div class="col-9">
                        @*These hide the values from the user, but allow the update button to pass the values back through the VM object*@
                        <input readonly type="hidden" asp-for="ReviewApplication.AppStatId" />
                        <input readonly type="hidden" asp-for="ReviewApplication.ApplicationId" />
                        <input readonly type="hidden" asp-for="ReviewApplication.UserID" />
                        <input readonly type="hidden" asp-for="ReviewApplication.StatusDate" />
                    </div>
                </div>

                <div class="form-group row m-2">
                    <div class="col-4">
                        <h4><label asp-for="ReviewApplication.StatusId">Status:</label></h4>
                    </div>
                    <div class="col-3">
                        @Html.DropDownListFor(m => m.ReviewApplication.StatusId,
                        Model.StatusList,
                        " - Please select a new status - ",
                        new { @class = "form-control", @id="ddlStatus" })
                        <span class="text-danger" asp-validation-for="ReviewApplication.StatusId"></span>
                    </div>
                </div>
                <div class="form-group row m-2">
                    <div class="col-9" style="border-top:1px solid #325d88">
                        <div class="row m-2">
                            <div class="col-2 offset-3">
                                <button type="submit" class="btn btn-primary form-control">Update</button>

                            </div>
                            <div class="col-3">
                                <a asp-controller="ReviewApplications" asp-action="Index" class="btn btn-success form-control">Back to List</a>
                            </div>
                            <div class="col-2">
                                <a asp-area="Mentor" asp-controller="MentorNotes" asp-action="Index" asp-route-appId="@Model.Application.Id" class="btn btn-primary">Notes</a>
                            </div>
                        </div>
                    </div>
                </div>
                </>
            </div>
        </div>
</form>