wildcatMicroFund/Models/ReadyEmail.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace wildcatMicroFund.Models
{
    public class ReadyEmail
    {
        [Key]
        public int Id { get; set; }
        public DateTime CreatedDate { get; set; }
        [EmailAddress]
        [Required]
        public string? ReadyEmailEmail { get; set; }
        [Required]
        public string? ReadyEmailSubject { get; set; }
        [Required]
        public string? ReadyEmailContent { get; set; }
        [ForeignKey("EmailTemplate")]
        public int EmailTemplateId { get; set; }
        public virtual EmailTemplate EmailTemplate { get; set; }
        [ForeignKey("ApplicationUser")]
        public string UserID { get; set; }
        public virtual ApplicationUser User { get; set; }

    }
}

wildcatMicroFund/Areas/Admin/Controllers/ReadyEmails/ReadyEmailsController.cs
using Microsoft.AspNetCore.Identity.UI.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Dynamic;
using System.Linq;
using wildcatMicroFund.Areas.Admin.ViewModels;
using wildcatMicroFund.Interfaces;
using wildcatMicroFund.Models;

[Area("Admin")]
public class ReadyEmailsController : Controller
{
    private readonly IEmailSender _emailSender;
    private readonly IUnitOfWork _unitOfWork;
    public ReadyEmailsController(IUnitOfWork unitOfWork, IEmailSender emailSender) 
    {
        _unitOfWork = unitOfWork;
        _emailSender = emailSender;
    }
    public UserEmailVM UserEmailObj { get; set; }
    public ViewResult Index()
    {
        IEnumerable<ReadyEmail> objReadyEmail = _unitOfWork.ReadyEmail.GetAll();
        IEnumerable<UserEmailVM> viewObj;
        List<UserEmailVM> viewList = new List<UserEmailVM>();
        foreach (ReadyEmail email in objReadyEmail) 
        {
            UserEmailObj = new UserEmailVM
            {
                ReadyEmail = email,
                User = _unitOfWork.ApplicationUser.Get(c => c.Id == email.UserID),
                EmailTemplate = _unitOfWork.EmailTemplate.Get(c => c.Id == email.EmailTemplateId)


            };
            System.Diagnostics.Debug.WriteLine("Email Template Name: "+UserEmailObj.EmailTemplate.EmailTemplateName);
            viewList.Add(UserEmailObj);
        }
        viewObj = viewList;
        return View(viewObj);
    }
    [HttpGet]
    public IActionResult Create() 
    {
        ViewBag.Users=GetUsers();
        ViewBag.EmailTemplates = GetEmailTemplates();
        return View();
    }
    [HttpPost]
    public IActionResult Create(ReadyEmail readyEmail) 
    {
        readyEmail.EmailTemplate = _unitOfWork.EmailTemplate.Get(c => c.Id == readyEmail.EmailTemplateId);
        readyEmail.User = _unitOfWork.ApplicationUser.Get(c => c.Id == readyEmail.UserID);
        if (readyEmail.User != null && readyEmail.EmailTemplate != null)
        {
            readyEmail.CreatedDate = DateTime.Now;
            readyEmail.ReadyEmailContent = _unitOfWork.ReadyEmail.InitializeEmail(readyEmail);
            readyEmail.ReadyEmailSubject = readyEmail.EmailTemplate.TemplateSubject;
            readyEmail.ReadyEmailEmail = readyEmail.User.Email;
            _unitOfWork.ReadyEmail.Add(readyEmail);
            _unitOfWork.Commit();
            TempData["success"] = "Email created Successfully";
            return RedirectToAction("Index");
        }
        return View(readyEmail);
    }
    [HttpGet]
    public IActionResult Edit(int? id)
    {
        if (id == null || id == 0)
        {
            return NotFound();
        }
        var readyEmail = _unitOfWork.ReadyEmail.Get(c => c.Id == id);
        if (readyEmail == null)
        {
            return NotFound();
        }
        return View(readyEmail);
    }
    [HttpGet]
    public IActionResult Delete(int? id)
    {
        if (id == null || id == 0)
        {
            return NotFound();
        }
        var readyEmailFromDb = _unitOfWork.ReadyEmail.Get(c => c.Id == id);
        if (readyEmailFromDb == null)
        {
            return NotFound();
        }
        return View(readyEmailFromDb);
    }
    [HttpGet]
    public async Task<IActionResult> Send(int? id)
    {
        //Currently Just deletes when sent
        var obj = _unitOfWork.ReadyEmail.Get(c => c.Id == id);
        if (obj == null)
        {
            return NotFound();
        }
        await _emailSender.SendEmailAsync(obj.ReadyEmailEmail, obj.ReadyEmailSubject, obj.ReadyEmailContent);
        _unitOfWork.ReadyEmail.Delete(obj);
        _unitOfWork.Commit();
        TempData["success"] = "ReadyEmail was deleted Successfully";
        return RedirectToAction("Index");
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public IActionResult Edit(ReadyEmail obj)
    {
        obj.CreatedDate = DateTime.Now;
        obj.User = _unitOfWork.ApplicationUser.Get(c => c.Id == obj.UserID);
        obj.EmailTemplate = _unitOfWork.EmailTemplate.Get(c => c.Id == obj.EmailTemplateId);
        //if (ModelState.IsValid)
        //{
        if (obj != null)
        {
            if (obj.EmailTemplate != null && obj.User != null)
            {
                if (obj.ReadyEmailContent != null && !obj.ReadyEmailContent.Equals(String.Empty))
                {
                    if (obj.ReadyEmailEmail != null && !obj.ReadyEmailEmail.Equals(String.Empty))
                    {
                        if (obj.ReadyEmailSubject != null && !obj.ReadyEmailSubject.Equals(String.Empty))
                        {
                            _unitOfWork.ReadyEmail.Update(obj);
                            _unitOfWork.Commit();
                            TempData["success"] = "Email Template updated Successfully";
                            return RedirectToAction("Index");
                            //}
                        }
                    }
                }
            }
        }

        return View(obj);
    }
    [HttpPost, ActionName("Delete")]
    public IActionResult DeletePost(int? id)
    {
        var obj = _unitOfWork.ReadyEmail.Get(c => c.Id == id);
        if (obj == null)
        {
            return NotFound();
        }
        _unitOfWork.ReadyEmail.Delete(obj);
        _unitOfWork.Commit();
        TempData["success"] = "ReadyEmail was deleted Successfully";
        return RedirectToAction("Index");
    }

    private List<SelectListItem> GetUsers() 
    {
        var lstUsers = new List<SelectListItem>();
        IEnumerable<ApplicationUser> users = _unitOfWork.ApplicationUser.GetAll();
        lstUsers = users.Select(u => new SelectListItem() 
        {
            Value = u.Id,
            Text = u.FullName
        }).ToList();
        var defItem = new SelectListItem()
        {
            Value="",
            Text ="----Select User----"
        };
        lstUsers.Insert(0, defItem);
        return lstUsers;
    }
    private List<SelectListItem> GetEmailTemplates()
    {
        var lstTemplates = new List<SelectListItem>();
        IEnumerable<EmailTemplate> templates = _unitOfWork.EmailTemplate.GetAll();
        lstTemplates = templates.Select(u => new SelectListItem()
        {
            Value = u.Id.ToString(),
            Text = u.EmailTemplateName
        }).ToList();
        var defItem = new SelectListItem()
        {
            Value = "",
            Text = "----Select Template----"
        };
        lstTemplates.Insert(0, defItem);
        return lstTemplates;
    }
}

wildcatMicroFund/Areas/Admin/Views/ReadyEmails/Create.cshtml
@model ReadyEmail
@{
    ViewData["Title"] = "Create";
}

<form method="post">
    <div class="border p-3 mt-4">
        <div class="row pb-2">
            <h2 class="text-primary">Create Template</h2>
            <hr />
        </div>
        @*<div asp-validation-summary="All"></div>*@
            <div class="form-group">
                <label asp-for="UserID" class="control-label"></label>
                <select asp-for="UserID" class="form-control" asp-items="ViewBag.Users"></select>
                <span asp-validation-for="UserID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EmailTemplateId" class="control-label"></label>
                <select asp-for="EmailTemplateId" class="form-control" asp-items="ViewBag.EmailTemplates"></select>
                <span asp-validation-for="EmailTemplateId" class="text-danger"></span>
            </div>
        <button type="submit" class="btn btn-primary" style="width:150px">Create</button>
        <a asp-controller="ReadyEmails" asp-action="Index" class="btn btn-secondary" style="width:150px">
            Back to List
        </a>
    </div>
</form>
@section Scripts {
    @{
        <partial name="_ValidationScriptsPartial" />
            <script>
      tinymce.init({
        selector: '#mytextarea'
      });
    </script>
    }
    }

wildcatMicroFund/Areas/Admin/Views/ReadyEmails/Delete.cshtml
@model ReadyEmail
@{
    ViewData["Title"] = "Delete Email";
}
<form method="post">
    <div class="border p-3 mt-4">
        <div class="row pb-2">
            <h2 class="text-primary">Delete Template</h2>
            <hr />
        </div>
        <!--Needed becasue all other items are disabled-->
        <input asp-for="Id" hidden />
        @*<div asp-validation-summary="All"></div>*@
        <div class="mb-3">

        </div>
        <div class="mb-3">
            <label asp-for="ReadyEmailContent"></label>
            <input asp-for="ReadyEmailContent" disabled class="form-control" />

        </div>
        <button type="submit" class="btn btn-danger" style="width:150px">Delete</button>
        <a asp-controller="ReadyEmails" asp-action="Index" class="btn btn-secondary" style="width:150px">
            Back to List
        </a>
    </div>
</form>

@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial" />
    }
    }

wildcatMicroFund/Areas/Admin/Views/ReadyEmails/Edit.cshtml
@model ReadyEmail
@{
    ViewData["Title"] = "Edit Email";
}
<form method="post">
    <div class="border p-3 mt-4">
        <div class="row pb-2">
            <h2 class="text-primary">Edit Template</h2>
            <hr />
        </div>
        @Html.HiddenFor(m => m.EmailTemplateId)
        @Html.HiddenFor(m => m.UserID)
        @*<div asp-validation-summary="All"></div>*@
        <div class="mb-3">
            <label asp-for="ReadyEmailEmail"></label>
            <input asp-for="ReadyEmailEmail" class="form-control" />
            <span asp-validation-for="ReadyEmailEmail" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="ReadyEmailSubject"></label>
            <input asp-for="ReadyEmailSubject" class="form-control" />
            <span asp-validation-for="ReadyEmailSubject" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="ReadyEmailContent"></label>
            @*<input asp-for="TemplateContent" class="form-control" />*@
            <textarea id="mytextarea" class="form-control" style="height:200px;" asp-for="ReadyEmailContent"></textarea>
            <span asp-validation-for="ReadyEmailContent" class="text-danger"></span>
        </div>
        <button type="submit" class="btn btn-primary" style="width:150px">Update</button>
        <a asp-controller="ReadyEmails" asp-action="Index" class="btn btn-secondary" style="width:150px">
            Back to List
        </a>
    </div>
</form>

@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial" />
                    <script>
      tinymce.init({
        selector: '#mytextarea'
      });
    </script>
    }
    }
    

wildcatMicroFund/Areas/Admin/Views/ReadyEmails/Index.cshtml
@model IEnumerable<wildcatMicroFund.Areas.Admin.ViewModels.UserEmailVM>
@{
    ViewData["Title"] = "Ready Emails";
}
<div class="container p-3">
    <div class="row pt-4">
        <div class="col-6">
            <h2 class="text-primary">Ready Emails</h2>
        </div>
        <div class="col-6 text-end">
            <a asp-controller="ReadyEmails" asp-action="Create" class="btn btn-primary">
                <i class="bi bi-plus-circle"></i>Create New Email
            </a>
        </div>
    </div>
    <br /><br />

    <table class="table table-bordered table-striped" style="width:100%">
        <thead>
            <tr>
                <th>
                    Name
                </th>
                <th>
                    Email
                </th>
                <th>
                    Template
                </th>
                <th>
                    Date
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var obj in Model)
            {
                <tr>
                    <td width="20%">
                        @obj.User.FullName
                    </td>
                    <td width="20%">
                        @obj.ReadyEmail.ReadyEmailEmail
                    </td>
                    <td width="20%">
                        @obj.EmailTemplate.EmailTemplateName
                    </td>
                        
                    <td>
                        @obj.ReadyEmail.CreatedDate.ToString("MM/dd/yyyy")
                    </td>
                    <td>
                        <div class="w-75 btn-group" role="group">
                            <a asp-controller="ReadyEmails" asp-action="Edit" asp-route-Id="@obj.ReadyEmail.Id"
                           class="btn btn-primary mx-2"> <i class="bi bi-pencil-square"></i> Edit</a>
                            <a asp-controller="ReadyEmails" asp-action="Delete" asp-route-Id="@obj.ReadyEmail.Id"
                           class="btn btn-danger mx-2"> <i class="bi bi-trash-fill"></i> Delete</a>
                           <a asp-controller="ReadyEmails" asp-action="Send" asp-route-Id="@obj.ReadyEmail.Id"
                           class="btn btn-primary mx-2"> <i class="bi bi-trash-fill"></i> Send</a>
                        </div>
                    </td>
                </tr>
            }
        </tbody>

    </table>
</div>